### ISSUE TITLE
App not recognizing presence of audio files

### ISSUE THREAD

**Issue by jejl** [BritishTrustForOrnithology/BTOAcousticPipelineVerificationApp#1]
When I select a directory containing audio files, no button appears to allow auditing.

![image](https://github.com/user-attachments/assets/4f807312-bd5e-46eb-9de7-451833b7d9ca)

**Comment by btosimongillings** [comment]
This should now be fixed. The shinyjs::show() function was masked preventing the button being displayed. If problems persist please let us know.
